# Generated by Django 4.0 on 2021-12-24 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='webdevelopment_details',
            fields=[
                ('did', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
                ('phone_no', models.IntegerField(unique=True)),
                ('gender', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'webdevelopment_details',
                'verbose_name_plural': 'webdevelopment_detailss',
            },
        ),
    ]
